### ISSUE TITLE
Add an optional field to provide json formatted parameters

### ISSUE THREAD

**Issue by IantoMcGuckin** [jenkinsci/testrail-plugin#21]
Add an optional Test Run Id to post results to

**Comment by IantoMcGuckin** [comment]
I've also had this feedback from my line manager:

One thing to note, it looks like the code only identifies Test CASES and does not work with TESTS. Looking at the TestRail API doc on results, (http://docs.gurock.com/testrail-api2/reference-results ) it clearly delineates methods for results for Tests vs Cases. My concern with this is that I’d like to be able to have test IDs associated with different releases. I don’t know TestRail well enough to know what happens if we never use the TestID vs CaseID for results reporting. Can you do the following experiment to see what happens:
Take one of your test suites/runs and execute it for 3 build/runs
a. Verify that it does NOT create new/unique tests for each run. (i.e. NO new Test ID # s for each run)
b. Verifying that each result appears as multiple results of the same test run (this is the desired behavior)
c. Then check the CASEs —from Test Suites & Cases tab, verify that there are only the results expected from the righthand Tests & Results
Close the test run that has the 3 build/runs data (the Lock Icon at the top of the Test Run view)
Then Run the build tests again to verify that new Test ID #’s are generated
a. If this does not seem correct to you, please hold off on pointing to Production until we can figure a consistent way of using TestRail for all the projects.
(right now I’m opening to have Test Plans and Runs closed as part of the release process so that the data is preserved and we have “new” starting point)
So, after trying the above (with the previous version of the plugin, due to the error reported in a comment above), I can see that (1a), for every run, we are creating new test IDs for the same test:

The test has 3 different IDs, one per run.

**Comment by IantoMcGuckin** [comment]
xirsoi - "As for Tests vs Cases, I'm aware of the distinction, and the current behavior of the plugin is as designed. It creates a new Test Run and applies results to that. Test Cases are like the definition of a class, a blueprint. Tests are the implementation of that blueprint.

I may be able to add an optional Test Run Id to post results to, instead of creating a new run, but that will not be an easy task as the code is very messy and hard to modify."

**Comment by xirsoi** [comment]
Please try this build: https://www.dropbox.com/s/10c1csk918w0kjw/testrail.hpi?dl=0

I'm having ssl errors trying to get to my testrail instance, so I'm having trouble testing it myself. But the change is super simple, so it *should* work, so long as you provide it a valid json object (see the help button for the parameters field.

**Comment by IantoMcGuckin** [comment]
Hi Adam,

I've just performed a quick test (I'm attending a 3-day Health & Safety in the Workplace study course this week Tue - Thu), and when adding in just the e.g. newly mandatory version field for now, against my testrail staging instance, it worked! Hurrah!

I have not yet tried the test run id - I'll give that a go tomorrow night after the course.

One tiny bug I found is that I can enter the new parameters in jenkins OK (inserts this line to the job's config.xml):

<extraParameters>{ &quot;version&quot;:&quot;7.3.0.25&quot; }</extraParameters>

which is fine, and as I say works (I can see this value reported for the tests in testrail - so it passed the mandatory field check and passed the value successfully).  But when I re-configure the job in Jenkins, the display of the extra parameters is blank - so it looks empty - but the above entry IS in the config.xml for the job.  So when it is converted and written as xml, the re-reading in of it to display in Jenkins seems to fail. 

Great progress!  Thank you!

**Comment by xirsoi** [comment]
That's very interesting, I may know where that problem is coming from.

Also, don't feel rushed to test anything, whenever works for you.

**Comment by xirsoi** [comment]
I think I've got it resolved, I'll do some testing tomorrow morning (~6am CST)

**Comment by xirsoi** [comment]
If you get a chance to test it before me: https://www.dropbox.com/s/812757c3w9t1ewd/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
Hi Adam - a quick test and the set value is still not displaying in Jenkins, tried re-entering the value and re-configuring the job - blank again

**Comment by xirsoi** [comment]
Ha, figured it out. I'll have a fix tonight.

**Comment by IantoMcGuckin** [comment]
Also, could you please clarify - how would I add the test run id in Jenkins:

"I may be able to add an optional Test Run Id to post results to, instead of creating a new run, but that will not be an easy task as the code is very messy and hard to modify"

**Comment by xirsoi** [comment]
That functionality is not yet available. I'll make a ticket for that later today.

**Comment by IantoMcGuckin** [comment]
Tried using system variables:

<extraParameters>{ &quot;version&quot;:&quot;$VERSION_NUMBER.$BUILD_NUMBER&quot; }</extraParameters>

results in:

![image](https://user-images.githubusercontent.com/29099191/27929074-6d67dd8c-6289-11e7-9ebf-9ccc4c937e92.png)

So these do not seem to work?

**Comment by xirsoi** [comment]
I suspect that wrapping the environment variable in quotes is your problem.
It should work fine without them, but I can't be certain. I think you might have to Google that one, if removing the quotes doesn't work.

This build should fix the params not showing up correctly: https://www.dropbox.com/s/93dcjj1yeqgnd9x/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
Hi - the new build has not fixed the display of the extra parameters.  

I've also tried 

{ &quot;version&quot;: $VERSION_NUMBER }

where $VERSION_NUMBER is defined in the config.xml for the job, in 
`<buildWrappers`>
    `<EnvInjectBuildWrapper plugin="envinject@2.1.3"`>
      `<info`>
        `<propertiesContent`> section

![image](https://user-images.githubusercontent.com/29099191/27951146-d2611e7a-62fb-11e7-8e63-b214ec690d55.png)

and the same happens for $BUILD_NUMBER - the global variable defined outside of the job's config.xml - so in each case the variable is not being passed, whether I use quotes or not, or try system variables that are defined at different levels, so I think it is just not working?

**Comment by IantoMcGuckin** [comment]
also, can I ask is there a way to add results against test runs in a test plan?

**Comment by xirsoi** [comment]
I don't know, I'll look into it when I get home. Any real work that would
require will have to wait awhile, I'm quite busy for the next two weeks.

**Comment by IantoMcGuckin** [comment]
sure, I was hoping it would be a simple case of adding a test plan id as an extra parameter?

**Comment by IantoMcGuckin** [comment]
Hi, really need some help with this, as I need to understand how the associations work - how to assign the results against a testsuite that is part of a testplan?

**Comment by xirsoi** [comment]
You mean a test run that is part of a test plan. That isn't currently possible, but #24 should allow that. I'll try to get that feature working this weekend.

**Comment by IantoMcGuckin** [comment]
Hi - any progress?

**Comment by xirsoi** [comment]
Couldn't get to it this weekend, but I should be able to tonight. I don't
know precisely what's up with the Json not saving, but posting results
against an existing test run should be relatively simple.

**Comment by IantoMcGuckin** [comment]
great, my line manager has decided that tomorrow is the deadline for getting all of my automated tests into testrail, so the ability to assign the test id will make this a reality, hoping for a celebration tomorrow!

**Comment by xirsoi** [comment]
The extra parameters are working, they even get saved like they're supposed to (not sure how I managed that one).
